-- V2__core_tables.sql
-- Phase 1 schema: the resource tree (floors → rooms → desks). No bookings yet.
-- desks.type is a TEXT + CHECK constraint rather than a Postgres ENUM so JPA can
-- map it as a plain @Enumerated(EnumType.STRING) without the Hibernate/PG-enum dance.

CREATE TABLE floors (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE rooms (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    floor_id BIGINT NOT NULL REFERENCES floors (id) ON DELETE CASCADE,
    name     TEXT   NOT NULL
);
CREATE INDEX idx_rooms_floor_id ON rooms (floor_id);

CREATE TABLE desks (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms (id) ON DELETE CASCADE,
    name    TEXT   NOT NULL,
    type    TEXT   NOT NULL CHECK (type IN ('STANDARD', 'STANDING', 'CONFERENCE'))
);
CREATE INDEX idx_desks_room_id ON desks (room_id);

-- Demo seed: 1 floor / 2 rooms / 6 desks with a mix of types.
INSERT INTO floors (id, name) VALUES
    (1, 'Floor 1');

INSERT INTO rooms (id, floor_id, name) VALUES
    (1, 1, 'Room 101'),
    (2, 1, 'Room 102');

INSERT INTO desks (id, room_id, name, type) VALUES
    (1, 1, 'Desk 101-A', 'STANDARD'),
    (2, 1, 'Desk 101-B', 'STANDARD'),
    (3, 1, 'Desk 101-C', 'STANDING'),
    (4, 2, 'Desk 102-A', 'STANDARD'),
    (5, 2, 'Desk 102-B', 'STANDING'),
    (6, 2, 'Desk 102-C', 'CONFERENCE');

-- Bump the identity sequences past the manually seeded IDs so future inserts don't collide.
SELECT setval(pg_get_serial_sequence('floors', 'id'), (SELECT MAX(id) FROM floors));
SELECT setval(pg_get_serial_sequence('rooms', 'id'), (SELECT MAX(id) FROM rooms));
SELECT setval(pg_get_serial_sequence('desks', 'id'), (SELECT MAX(id) FROM desks));
